/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as HiRouteImport } from './routes/hi'
import { Route as BlaRouteImport } from './routes/bla'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestHiRouteImport } from './routes/test/hi'
import { Route as TestFooRouteImport } from './routes/test/foo'
import { ServerRoute as HelloServerRouteImport } from './routes/hello'

const rootServerRouteImport = createServerRootRoute()

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const HiRoute = HiRouteImport.update({
  id: '/hi',
  path: '/hi',
  getParentRoute: () => rootRouteImport,
} as any)
const BlaRoute = BlaRouteImport.update({
  id: '/bla',
  path: '/bla',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestHiRoute = TestHiRouteImport.update({
  id: '/hi',
  path: '/hi',
  getParentRoute: () => TestRoute,
} as any)
const TestFooRoute = TestFooRouteImport.update({
  id: '/foo',
  path: '/foo',
  getParentRoute: () => TestRoute,
} as any)
const HelloServerRoute = HelloServerRouteImport.update({
  id: '/hello',
  path: '/hello',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bla': typeof BlaRoute
  '/hi': typeof HiRoute
  '/test': typeof TestRouteWithChildren
  '/test/foo': typeof TestFooRoute
  '/test/hi': typeof TestHiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bla': typeof BlaRoute
  '/hi': typeof HiRoute
  '/test': typeof TestRouteWithChildren
  '/test/foo': typeof TestFooRoute
  '/test/hi': typeof TestHiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bla': typeof BlaRoute
  '/hi': typeof HiRoute
  '/test': typeof TestRouteWithChildren
  '/test/foo': typeof TestFooRoute
  '/test/hi': typeof TestHiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bla' | '/hi' | '/test' | '/test/foo' | '/test/hi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bla' | '/hi' | '/test' | '/test/foo' | '/test/hi'
  id: '__root__' | '/' | '/bla' | '/hi' | '/test' | '/test/foo' | '/test/hi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlaRoute: typeof BlaRoute
  HiRoute: typeof HiRoute
  TestRoute: typeof TestRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/hello': typeof HelloServerRoute
}
export interface FileServerRoutesByTo {
  '/hello': typeof HelloServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/hello': typeof HelloServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/hello'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/hello'
  id: '__root__' | '/hello'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  HelloServerRoute: typeof HelloServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hi': {
      id: '/hi'
      path: '/hi'
      fullPath: '/hi'
      preLoaderRoute: typeof HiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bla': {
      id: '/bla'
      path: '/bla'
      fullPath: '/bla'
      preLoaderRoute: typeof BlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/hi': {
      id: '/test/hi'
      path: '/hi'
      fullPath: '/test/hi'
      preLoaderRoute: typeof TestHiRouteImport
      parentRoute: typeof TestRoute
    }
    '/test/foo': {
      id: '/test/foo'
      path: '/foo'
      fullPath: '/test/foo'
      preLoaderRoute: typeof TestFooRouteImport
      parentRoute: typeof TestRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/hello': {
      id: '/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface TestRouteChildren {
  TestFooRoute: typeof TestFooRoute
  TestHiRoute: typeof TestHiRoute
}

const TestRouteChildren: TestRouteChildren = {
  TestFooRoute: TestFooRoute,
  TestHiRoute: TestHiRoute,
}

const TestRouteWithChildren = TestRoute._addFileChildren(TestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlaRoute: BlaRoute,
  HiRoute: HiRoute,
  TestRoute: TestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  HelloServerRoute: HelloServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
